### ISSUE TITLE
Request: build script for emscripten

### ISSUE THREAD

**Issue by stevedekorte** [sin-ack/zigself#22]
Is there already one? I didn't see any mention of emscripten or emscripten.h in the repo.

**Comment by sin-ack** [comment]
The good news is that we don't need Emscripten, since Zig can directly target WASM. The bad news is that we need to refactor the system call primitives to either be OS agnostic or enable/disable them based on OS at compile time before we can compile to WASM. It's on my list of things to do, I will get around to it sooner or later.

If you'd like to help with it, it would be very much appreciated.

**Comment by stevedekorte** [comment]
Thanks for the response. Have you considered simplifying the problem by solely targeting WASM? If you already have a large user base, I can understand why that would be an issue. Otherwise, maybe it would help attract interest.

**Comment by sin-ack** [comment]
From what I can tell, the users of ZigSelf can be counted on one hand including myself :) but I want to keep things native, with WASM also being a primary goal. I do want to have a Self world running within the browser, but that's a goal that's in parallel with fully native ZigSelf with multi-threaded actor scheduling.
